### ISSUE TITLE
Trying to build on Jetson TX2 errors during ninja build.

### ISSUE THREAD

**Issue by griz1112** [shortstheory/adaptive-streaming#1]
../src/RTSP_Stream_Server/IPCMessageHandler.cpp: In member function ‘std::__cxx11::string IPCMessageHandler::serialise_device_props(std::pair<std::__cxx11::basic_string<char>, v4l2_info>)’:
../src/RTSP_Stream_Server/IPCMessageHandler.cpp:62:50: error: format ‘%u’ expects argument of type ‘unsigned int’, but argument 9 has type ‘guint64 {aka long unsigned int}’ [-Werror=format=]
             stream->file_recorder.get_recording());
How do I fix this?

**Comment by griz1112** [comment]
Added ifdef for aarch64 using same code as amd64 fixed the error. %lu instead of %llu. One other problem in Common/GeneralAdaptiveStreaming.cpp line 60 No MAX_STEADY_BITRATE in this scope. Fixed temp by just putting 4000 in for that variable. This gets it to compile on the TX2. I'll update after testing it.

**Comment by griz1112** [comment]
Add AARCH64 to Constants.h so MAX_STEADY_BITRATE is defined for the jetson. Compiles cleanly after these two changes.

**Comment by shortstheory** [comment]
Thanks for this. Could you file a PR with your change so I can merge it back to master?

**Comment by shortstheory** [comment]
This has been fixed in the latest commit to master which has added Jetson support.
