### ISSUE TITLE
error in device  file reading 

### ISSUE THREAD

**Issue by profff** [shortstheory/adaptive-streaming#12]
I've try to follow error and it looks when creating AdaptiveStream object 
I've setup a fresh raspian buster install on rpi4

<pre><font color="#3465A4"><b>$</b></font> meson build
<b>The Meson build system</b>
Version: 0.52.1
Source dir: <b>/home/pi/APStreamline</b>
Build dir: <b>/home/pi/APStreamline/build</b>
Build type: <b>native build</b>
Project name: <b>adaptive-streaming</b>
Project version: <b>undefined</b>
C compiler for the host machine: <b>cc</b> (gcc 8.3.0 &quot;cc (Raspbian 8.3.0-6+rpi1) 8.3.0&quot;)
C linker for the host machine: <b>GNU ld.bfd</b> 2.31.1
C++ compiler for the host machine: <b>c++</b> (gcc 8.3.0 &quot;c++ (Raspbian 8.3.0-6+rpi1) 8.3.0&quot;)
C++ linker for the host machine: <b>GNU ld.bfd</b> 2.31.1
Host machine cpu family: <b>arm</b>
Host machine cpu: <b>armv7l</b>
Found pkg-config: <b>/usr/bin/pkg-config</b> (0.29)
Run-time dependency <b>gstreamer-1.0</b> found: <font color="#4E9A06"><b>YES</b></font> 1.14.4
Run-time dependency <b>gstreamer-rtp-1.0</b> found: <font color="#4E9A06"><b>YES</b></font> 1.14.4
Run-time dependency <b>gstreamer-rtsp-1.0</b> found: <font color="#4E9A06"><b>YES</b></font> 1.14.4
Run-time dependency <b>gstreamer-rtsp-server-1.0</b> found: <font color="#4E9A06"><b>YES</b></font> 1.14.4
Run-time dependency <b>threads</b> found: <font color="#4E9A06"><b>YES</b></font> 
Run-time dependency <b>libconfig++</b> found: <font color="#4E9A06"><b>YES</b></font> 1.5
Build targets in project: <b>1</b>
Found ninja-1.8.2 at /usr/bin/ninja
<font color="#4E9A06"><b>pi@raspberrypi</b></font>:<font color="#3465A4"><b>~/APStreamline $</b></font> cd build/
<font color="#4E9A06"><b>pi@raspberrypi</b></font>:<font color="#3465A4"><b>~/APStreamline/build $</b></font> ninja
[14/14] Linking target stream_server.
<font color="#4E9A06"><b>pi@raspberrypi</b></font>:<font color="#3465A4"><b>~/APStreamline/build $</b></font> ./stream_server wlan0
&quot;/home/pi/APStreamline/build&quot;
Interface : wlan0
Address : 192.168.0.20
***APStreamline***
Access the following video streams using VLC or gst-launch following the instructions here: https://github.com/shortstheory/adaptive-streaming#usage
==============================
Reading RPi config
I/O error while reading file.
terminate called after throwing an instance of &apos;std::out_of_range&apos;
  what():  _Map_base::at
Aborted
<font color="#4E9A06"><b>pi@raspberrypi</b></font>:<font color="#3465A4"><b>~/APStreamline/build $</b></font> uname -a
Linux raspberrypi 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux
</pre>

**Comment by profff** [comment]
it looks to comes with v2 as my fork from last release still works well

**Comment by shortstheory** [comment]
Hi, yes, in the v2 build, you must run the executable from the same folder as the `config` folder. So instead of `./stream_server wlan0`, do:

```
cd ..
./build/stream_server wlan0
```

**Comment by profff** [comment]
Oh ok sory for that mistake i will retry this asap (for now I stick to thé
v1 )

Le jeu. 5 nov. 2020 à 16:18, arnav dhamija <notifications@github.com> a
écrit :
