### ISSUE TITLE
video 180° reversed with 2.0 on raspberry pi CSI cam

### ISSUE THREAD

**Issue by profff** [shortstheory/adaptive-streaming#13]
when using v2 the video is 180° return (upside down) 
when shutting down v2 and start v1 it gets back in the right way
when shutting down v1 and restart v2 it's in the right way too until next reboot 
looks that v1 is doing something on V4L driver for the rpi cam but I dont know what

**Comment by shortstheory** [comment]
Yes, this a known issue with v2. The RPi camra requires an IOCTL for adjusting the video flip. I will be fixing this soon. Thank you for reporting!

**Comment by shortstheory** [comment]
This issue is now resolved with the latest commit. Do let me know if you face any other issues!

**Comment by profff** [comment]
great !! thank's a lot it works perfectly !
