### ISSUE TITLE
Ras Pi Quality Issue

### ISSUE THREAD

**Issue by stephendade** [shortstheory/adaptive-streaming#3]
Running on a Raspberry Pi, the automatic quality/resolution changes are not occurring. I attempted to instead force a resolution change via the APWeb interface but got a system crash instead.

Using a previous commit (d6efd60548dfd34177b47f229ba594fa95a45498), the quality changes (automatic and forced) work fine. So I'm thinking it must have broken somewhere between then and now.

**Comment by shortstheory** [comment]
Thank you for informing me. I don't have access to an RPi at the moment, but this is the first thing I will look at when I'm back to my regular setup in a few weeks. There was a major overhaul to the code to support aarch64 like the Jetson TX2 and I've only tested the TX2 and software encoding on my laptop. I suspect I might have broken something in the rewrite.

**Comment by shortstheory** [comment]
@stephendade Can you share your GStreamer version, OS, and type of  RPi?

**Comment by stephendade** [comment]
Rpi 3B+
```
pi@apsync:~ $ uname -a
Linux apsync 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
pi@apsync:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"


```

Gstreamer version is 1.14.1

**Comment by shortstheory** [comment]
Hi, I'm back to test things out. May I know how you installed GStreamer 1.14.1? After updating all the packages on my Pi, the latest version I can install is GStreamer 1.10.4. As far as I can see, things still work fine on 1.10.4 so I think something might have broken with 1.14.1 because it handles multiudpsink differently from the previous versions.

**Comment by stephendade** [comment]
Ahh, I thought you meant the version on my PC receiving the stream.

For the pi, I just had the latest version installed via apt-get. I'm overseas for a conference this week, so don't have my Pi with me. I'll get a version number next week when I'm back.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
